### ISSUE TITLE
Mixed return values with colors_returned option

### ISSUE THREAD

**Issue by rikukissa** [Fooidge/PleaseJS#26]
> colors_returned: (1-infinity) Setting colors_returned to higher than 1 will return an array full of the colors Please has made for you. If you set it to 1, you'll just get the one color! It makes a sort of sense if you think about it.

In my opinion it would make a lot of more sense if the function would always return an array of strings when the color_returned is used.

In many use cases the number comes from a dynamic value and now the result needs to be converted for consistent results.

**Comment by jmanuel1** [comment]
I see three options here:
- Change the function to always return an array (so that people don't have to convert the return value for consistent results)
- Don't change the function (I think this makes the return value more intuitive)
- Make a wrapper around the function that always returns an array (best of both worlds, might seem like overkill)

That's just my opinion, of course.

**Comment by rikukissa** [comment]
How is returning mixed type values intuitive? In my opinion functions should always return same type values.

**Comment by NadyaNayme** [comment]
I agree with @rikukissa here. The function should always return an array for consistent results.

**Comment by Fooidge** [comment]
I'll just make it always return an array it's NBD. I was trying to save people time but if it ends up being a pain it's clearly not operating as designed. 

Jordan Checkman

**Comment by rikukissa** [comment]
:+1:

**Comment by jmanuel1** [comment]
Fine by me.
